import { Event } from '@/types/event';

export const MOCK_EVENTS: Event[] = [
  {
    id: '1',
    slug: 'jazz-night-indiranagar',
    title: 'Jazz Night at Indiranagar',
    titleKn: 'ಇಂಡಿರಾನಗರದಲ್ಲಿ ಜಾಝ್ ರಾತ್ರಿ',
    titleHi: 'इंदिरानगर में जैज़ नाइट',
    titleTa: 'இந்திரா நகர் ஜாஸ் நைட்',
    description:
      'An intimate evening of live jazz featuring the Bangalore Jazz Quartet. Expect smooth tunes, signature cocktails, and a warm ambient atmosphere at one of Indiranagar\'s most loved venues.',
    category: 'Music',
    date: '2026-05-10',
    startTime: '19:30',
    endTime: '22:00',
    timeOfDay: 'evening',
    venue: {
      name: 'The Humming Tree',
      address: '12/1, Wood Street, Ashok Nagar, Indiranagar, Bangalore',
      zone: 'East Bangalore',
      lat: 12.9784,
      lng: 77.6408,
    },
    organizer: { id: 'o1', name: 'Bangalore Live Events', verified: true },
    imageUrl: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800&q=80',
    tags: ['jazz', 'live music', 'cocktails', 'intimate'],
    isFeatured: false,
    isSoldOut: false,
    tiers: [
      { id: 't1', label: 'General Admission', priceInr: 799, totalSeats: 80, availableSeats: 34 },
      { id: 't2', label: 'VIP Table (2 persons)', priceInr: 2499, totalSeats: 10, availableSeats: 4 },
    ],
    minPriceInr: 799,
  },
  {
    id: '2',
    slug: 'canvas-comedy-club',
    title: 'Canvas Comedy Club',
    titleHi: 'कैनवस कॉमेडी क्लब',
    titleKn: 'ಕ್ಯಾನ್ವಾಸ್ ಕಾಮಿಡಿ ಕ್ಲಬ್',
    titleTa: 'கேன்வாஸ் காமெடி கிளப்',
    description:
      'Bangalore\'s top stand-up comedians take the stage for a night of unfiltered laughs. Featuring 5 acts, this 90-minute show is guaranteed to leave you in splits.',
    category: 'Comedy',
    date: '2026-05-11',
    startTime: '20:00',
    endTime: '22:00',
    timeOfDay: 'night',
    venue: {
      name: 'Canvas Laugh Club',
      address: '4th Floor, UB City Mall, Vittal Mallya Road, Central Bangalore',
      zone: 'Central Bangalore',
      lat: 12.9719,
      lng: 77.5937,
    },
    organizer: { id: 'o2', name: 'Canvas Entertainment', verified: true },
    imageUrl: 'https://images.unsplash.com/photo-1527224538127-2104bb71c51b?w=800&q=80',
    tags: ['comedy', 'stand-up', 'nightlife'],
    isFeatured: false,
    isSoldOut: false,
    tiers: [
      { id: 't3', label: 'Standard', priceInr: 499, totalSeats: 120, availableSeats: 67 },
      { id: 't4', label: 'Premium Front Row', priceInr: 799, totalSeats: 20, availableSeats: 8 },
    ],
    minPriceInr: 499,
  },
  {
    id: '3',
    slug: 'craft-beer-fest-ub-city',
    title: 'Craft Beer Fest — UB City',
    titleHi: 'क्राफ्ट बीयर फेस्ट — यूबी सिटी',
    description:
      'Sample 30+ craft beers from 12 independent Indian breweries. Live music, food trucks, and meet-the-brewer sessions make this the best beer event in Bangalore this month.',
    category: 'Food & Drink',
    date: '2026-05-17',
    startTime: '14:00',
    endTime: '21:00',
    timeOfDay: 'afternoon',
    venue: {
      name: 'UB City Piazza',
      address: 'UB City, 24 Vittal Mallya Road, Central Bangalore',
      zone: 'Central Bangalore',
      lat: 12.9715,
      lng: 77.5935,
    },
    organizer: { id: 'o3', name: 'IndiBrew Collective', verified: true },
    imageUrl: 'https://images.unsplash.com/photo-1436076863939-06870fe779c2?w=800&q=80',
    tags: ['beer', 'craft', 'food trucks', 'outdoor'],
    isFeatured: false,
    isSoldOut: false,
    tiers: [
      { id: 't5', label: 'Entry + 5 Tokens', priceInr: 1200, totalSeats: 500, availableSeats: 312 },
      { id: 't6', label: 'VIP + 15 Tokens + Food', priceInr: 2499, totalSeats: 50, availableSeats: 22 },
    ],
    minPriceInr: 1200,
  },
  {
    id: '4',
    slug: 'cyclothon-nandi-hills',
    title: 'Cyclothon — Nandi Hills',
    titleHi: 'साइक्लोथॉन — नंदी हिल्स',
    description:
      'A 42 km cycling event from Devanahalli to the Nandi Hills summit. Suitable for intermediate to advanced cyclists. Breakfast and finisher medal included. Helmets mandatory.',
    category: 'Sports',
    date: '2026-05-18',
    startTime: '06:00',
    endTime: '11:00',
    timeOfDay: 'morning',
    venue: {
      name: 'Devanahalli Town Square',
      address: 'Devanahalli, North Bangalore',
      zone: 'North Bangalore',
      lat: 13.2479,
      lng: 77.7156,
    },
    organizer: { id: 'o4', name: 'Bangalore Cycling Club', verified: false },
    imageUrl: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800&q=80',
    tags: ['cycling', 'outdoors', 'fitness', 'nandi hills'],
    isFeatured: false,
    isSoldOut: false,
    tiers: [
      { id: 't7', label: 'Registration', priceInr: 350, totalSeats: 200, availableSeats: 88 },
    ],
    minPriceInr: 350,
  },
  {
    id: '5',
    slug: 'bangalore-photo-walk',
    title: 'Bangalore Photo Walk — Pete\'s Alley',
    titleKn: 'ಬೆಂಗಳೂರು ಫೋಟೋ ವಾಕ್',
    description:
      'A guided 3-hour photo walk through Pete\'s Alley and Shivajinagar market. Open to all skill levels — bring your phone or DSLR. The walk ends with a chai break and photo review session.',
    category: 'Art',
    date: '2026-05-12',
    startTime: '07:00',
    endTime: '10:00',
    timeOfDay: 'morning',
    venue: {
      name: 'Pete\'s Alley, Shivajinagar',
      address: 'Pete\'s Alley, Shivajinagar, Central Bangalore',
      zone: 'Central Bangalore',
      lat: 12.9871,
      lng: 77.6,
    },
    organizer: { id: 'o5', name: 'Bangalore Street Lens', verified: false },
    imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80',
    tags: ['photography', 'walk', 'street art', 'free'],
    isFeatured: false,
    isSoldOut: false,
    tiers: [
      { id: 't8', label: 'Free Entry (register)', priceInr: 0, totalSeats: 30, availableSeats: 14 },
    ],
    minPriceInr: 0,
  },
  {
    id: '6',
    slug: 'ibsen-kannada-ranga-shankara',
    title: 'A Doll\'s House — Kannada Adaptation',
    titleKn: 'ಗೊಂಬೆಯ ಮನೆ — ರಂಗ ಶಂಕರ',
    description:
      'Ranga Shankara presents a compelling Kannada adaptation of Ibsen\'s classic. Directed by Prakash Belawadi, this production explores identity and freedom in a contemporary Bangalore setting.',
    category: 'Theatre',
    date: '2026-05-09',
    startTime: '19:00',
    endTime: '21:30',
    timeOfDay: 'evening',
    venue: {
      name: 'Ranga Shankara',
      address: '36/2, 8th Cross, JP Nagar 2nd Phase, South Bangalore',
      zone: 'South Bangalore',
      lat: 12.9087,
      lng: 77.5847,
    },
    organizer: { id: 'o6', name: 'Ranga Shankara', verified: true },
    imageUrl: 'https://images.unsplash.com/photo-1507924538820-ede94a04019d?w=800&q=80',
    tags: ['theatre', 'kannada', 'drama', 'ibsen'],
    isFeatured: false,
    isSoldOut: false,
    tiers: [
      { id: 't9', label: 'General', priceInr: 300, totalSeats: 200, availableSeats: 55 },
    ],
    minPriceInr: 300,
  },
  {
    id: '7',
    slug: 'skyye-rooftop-saturday',
    title: 'Skyye Rooftop Saturday',
    titleHi: 'स्काई रूफटॉप सैटरडे',
    description:
      'Bangalore\'s most popular rooftop party returns. DJ sets, sky-high cocktails, and panoramic city views. Dress code: smart casual. Entry includes a welcome drink.',
    category: 'Nightlife',
    date: '2026-05-16',
    startTime: '21:00',
    endTime: '02:00',
    timeOfDay: 'night',
    venue: {
      name: 'Skyye — UB City',
      address: '7th Floor, UB City, Vittal Mallya Road, Central Bangalore',
      zone: 'Central Bangalore',
      lat: 12.9718,
      lng: 77.5938,
    },
    organizer: { id: 'o7', name: 'Skyye Events', verified: true },
    imageUrl: 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&q=80',
    tags: ['nightlife', 'dj', 'rooftop', 'cocktails'],
    isFeatured: false,
    isSoldOut: true,
    tiers: [
      { id: 't10', label: 'Stag Entry', priceInr: 999, totalSeats: 100, availableSeats: 0 },
      { id: 't11', label: 'Couple Entry', priceInr: 1499, totalSeats: 50, availableSeats: 0 },
    ],
    minPriceInr: 999,
  },
  {
    id: '8',
    slug: 'lil-chefs-cooking-class',
    title: 'Lil\' Chefs — Kids Cooking Class',
    titleKn: 'ಮಕ್ಕಳ ಅಡುಗೆ ತರಗತಿ',
    description:
      'A fun 2-hour cooking class for kids aged 6–14. Children will make pizza, fruit chaat, and mango lassi under expert guidance. Aprons and ingredients provided. Parents welcome to watch.',
    category: 'Kids',
    date: '2026-05-14',
    startTime: '10:00',
    endTime: '12:00',
    timeOfDay: 'morning',
    venue: {
      name: 'The Kitchen Studio, Koramangala',
      address: '80 Feet Road, 4th Block, Koramangala, East Bangalore',
      zone: 'East Bangalore',
      lat: 12.9352,
      lng: 77.6245,
    },
    organizer: { id: 'o8', name: 'Lil\' Chefs Academy', verified: false },
    imageUrl: 'https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=800&q=80',
    tags: ['kids', 'cooking', 'family', 'workshop'],
    isFeatured: false,
    isSoldOut: false,
    tiers: [
      { id: 't12', label: 'Per Child', priceInr: 650, totalSeats: 20, availableSeats: 9 },
    ],
    minPriceInr: 650,
  },
  {
    id: '9',
    slug: 'morning-yoga-cubbon-park',
    title: 'Morning Yoga at Cubbon Park',
    titleKn: 'ಕಬ್ಬನ್ ಪಾರ್ಕ್‌ನಲ್ಲಿ ಬೆಳಗಿನ ಯೋಗ',
    titleHi: 'कब्बन पार्क में सुबह की योगा',
    description:
      'A free, open-air yoga session in the heart of Bangalore. Suitable for all levels. Bring your own mat. The session is guided by a certified Iyengar yoga instructor.',
    category: 'Wellness',
    date: '2026-05-13',
    startTime: '06:30',
    endTime: '08:00',
    timeOfDay: 'morning',
    venue: {
      name: 'Cubbon Park — Band Stand Lawn',
      address: 'Kasturba Road, Cubbon Park, Central Bangalore',
      zone: 'Central Bangalore',
      lat: 12.9763,
      lng: 77.5929,
    },
    organizer: { id: 'o9', name: 'Bangalore Yoga Collective', verified: false },
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80',
    tags: ['yoga', 'free', 'outdoors', 'wellness', 'morning'],
    isFeatured: false,
    isSoldOut: false,
    tiers: [
      { id: 't13', label: 'Free (register)', priceInr: 0, totalSeats: 50, availableSeats: 23 },
    ],
    minPriceInr: 0,
  },
  {
    id: '10',
    slug: 'prism-electronic-music-festival',
    title: 'Prism Electronic Music Festival',
    titleHi: 'प्रिज्म इलेक्ट्रॉनिक म्यूज़िक फेस्टिवल',
    titleKn: 'ಪ್ರಿಸಂ ಎಲೆಕ್ಟ್ರಾನಿಕ್ ಮ್ಯೂಸಿಕ್ ಫೆಸ್ಟಿವಲ್',
    description:
      'Bangalore\'s biggest electronic music festival returns for its 5th edition. 3 stages, 20+ artists, camping zone, art installations, and food village. Headlined by BLOT! and Oceantied.',
    category: 'Music',
    date: '2026-05-24',
    startTime: '14:00',
    endTime: '02:00',
    timeOfDay: 'afternoon',
    venue: {
      name: 'NICE Road Grounds',
      address: 'Tumkur Road, North Bangalore',
      zone: 'North Bangalore',
      lat: 13.0667,
      lng: 77.5565,
    },
    organizer: { id: 'o10', name: 'Prism Collective', verified: true },
    imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80',
    tags: ['electronic', 'festival', 'camping', 'edm', 'outdoor'],
    isFeatured: true,
    isSoldOut: false,
    tiers: [
      { id: 't14', label: 'Day Pass', priceInr: 2500, totalSeats: 2000, availableSeats: 834 },
      { id: 't15', label: 'Weekend Pass (2 days)', priceInr: 4000, totalSeats: 500, availableSeats: 211 },
      { id: 't16', label: 'VIP Pass + Lounge', priceInr: 6500, totalSeats: 100, availableSeats: 38 },
    ],
    minPriceInr: 2500,
  },
  {
    id: '11',
    slug: 'open-mic-humming-tree',
    title: 'Open Mic Night — The Humming Tree',
    titleKn: 'ಓಪನ್ ಮೈಕ್ ನೈಟ್',
    description:
      'An open stage for comedians, poets, and musicians. Sign up on the door to perform or just come to enjoy 15+ acts in a cozy bar setting. All genres, all levels welcome.',
    category: 'Comedy',
    date: '2026-05-15',
    startTime: '20:30',
    endTime: '23:00',
    timeOfDay: 'night',
    venue: {
      name: 'The Humming Tree',
      address: '12/1, Wood Street, Ashok Nagar, Indiranagar, Bangalore',
      zone: 'East Bangalore',
      lat: 12.9784,
      lng: 77.6408,
    },
    organizer: { id: 'o1', name: 'Bangalore Live Events', verified: true },
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80',
    tags: ['open mic', 'comedy', 'poetry', 'music'],
    isFeatured: false,
    isSoldOut: false,
    tiers: [
      { id: 't17', label: 'Walk-in Entry', priceInr: 200, totalSeats: 80, availableSeats: 45 },
    ],
    minPriceInr: 200,
  },
  {
    id: '12',
    slug: 'biryani-trail-shivajinagar',
    title: 'Biryani Trail: Shivajinagar',
    titleHi: 'बिरयानी ट्रेल: शिवाजीनगर',
    titleKn: 'ಬಿರಿಯಾನಿ ಟ್ರೇಲ್: ಶಿವಾಜಿನಗರ',
    titleTa: 'பிரியாணி டிரெய்ல்: ஷிவாஜிநகர்',
    description:
      'A 3-hour food walk through Shivajinagar sampling 6 legendary biryani spots. Your guide is a food historian who will share the Mughal and Deccani roots of each dish. Max 15 participants.',
    category: 'Food & Drink',
    date: '2026-05-21',
    startTime: '11:00',
    endTime: '14:00',
    timeOfDay: 'morning',
    venue: {
      name: 'Shivajinagar Bus Stand Entrance',
      address: 'Shivajinagar, Central Bangalore',
      zone: 'Central Bangalore',
      lat: 12.9858,
      lng: 77.6027,
    },
    organizer: { id: 'o11', name: 'Bangalore Food Stories', verified: true },
    imageUrl: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=800&q=80',
    tags: ['biryani', 'food walk', 'history', 'shivajinagar'],
    isFeatured: false,
    isSoldOut: false,
    tiers: [
      { id: 't18', label: 'Per Person', priceInr: 899, totalSeats: 15, availableSeats: 6 },
    ],
    minPriceInr: 899,
  },
  {
    id: '13',
    slug: 'bbmp-marathon-10k',
    title: 'BBMP Marathon 10K',
    titleKn: 'ಬಿಬಿಎಂಪಿ ಮ್ಯಾರಥಾನ್ 10ಕೆ',
    description:
      'The annual BBMP-sponsored 10K run through MG Road and Brigade Road. Chip-timed with finisher medals, T-shirt, and post-race banana and coconut water. Age 16+.',
    category: 'Sports',
    date: '2026-05-25',
    startTime: '06:00',
    endTime: '10:00',
    timeOfDay: 'morning',
    venue: {
      name: 'Kanteerava Stadium',
      address: 'Kasturba Road, Central Bangalore',
      zone: 'Central Bangalore',
      lat: 12.9741,
      lng: 77.5936,
    },
    organizer: { id: 'o12', name: 'BBMP Sports Division', verified: true },
    imageUrl: 'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=800&q=80',
    tags: ['running', 'marathon', '10k', 'fitness'],
    isFeatured: false,
    isSoldOut: false,
    tiers: [
      { id: 't19', label: 'Registration (incl. T-shirt)', priceInr: 400, totalSeats: 3000, availableSeats: 1422 },
    ],
    minPriceInr: 400,
  },
  {
    id: '14',
    slug: 'mandala-art-workshop',
    title: 'Mandala Art Workshop',
    titleKn: 'ಮಂಡಲ ಕಲಾ ಕಾರ್ಯಾಗಾರ',
    titleHi: 'मंडला आर्ट वर्कशॉप',
    description:
      'Learn the meditative art of mandala drawing. All materials provided. No prior art experience needed. The session covers geometry, colour theory, and symmetry patterns. Take home your finished artwork.',
    category: 'Art',
    date: '2026-05-20',
    startTime: '16:00',
    endTime: '19:00',
    timeOfDay: 'evening',
    venue: {
      name: 'The Atelier, Malleshwaram',
      address: '11th Cross, Malleshwaram, West Bangalore',
      zone: 'West Bangalore',
      lat: 13.003,
      lng: 77.5658,
    },
    organizer: { id: 'o13', name: 'The Atelier Studio', verified: false },
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    tags: ['art', 'workshop', 'mandala', 'meditation'],
    isFeatured: false,
    isSoldOut: false,
    tiers: [
      { id: 't20', label: 'Per Person (materials included)', priceInr: 750, totalSeats: 15, availableSeats: 7 },
    ],
    minPriceInr: 750,
  },
  {
    id: '15',
    slug: 'kids-theatre-panchatantra',
    title: 'Kids Theatre: Panchatantra Stories',
    titleKn: 'ಮಕ್ಕಳ ರಂಗಭೂಮಿ: ಪಂಚತಂತ್ರ',
    titleHi: 'बच्चों का नाटक: पंचतंत्र',
    titleTa: 'குழந்தைகள் நாடகம்: பஞ்சதந்திரம்',
    description:
      'A vibrant bilingual (Kannada + English) theatre performance of three Panchatantra tales for children aged 4–12. Interactive storytelling with puppets, songs, and audience participation.',
    category: 'Kids',
    date: '2026-05-22',
    startTime: '11:00',
    endTime: '12:30',
    timeOfDay: 'morning',
    venue: {
      name: 'Ranga Shankara',
      address: '36/2, 8th Cross, JP Nagar 2nd Phase, South Bangalore',
      zone: 'South Bangalore',
      lat: 12.9087,
      lng: 77.5847,
    },
    organizer: { id: 'o6', name: 'Ranga Shankara', verified: true },
    imageUrl: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&q=80',
    tags: ['kids', 'theatre', 'panchatantra', 'family'],
    isFeatured: false,
    isSoldOut: false,
    tiers: [
      { id: 't21', label: 'Child', priceInr: 250, totalSeats: 100, availableSeats: 58 },
      { id: 't22', label: 'Adult Companion', priceInr: 150, totalSeats: 100, availableSeats: 58 },
    ],
    minPriceInr: 150,
  },
];

export function getEventById(id: string): Event | undefined {
  return MOCK_EVENTS.find((e) => e.id === id);
}

export function getEventBySlug(slug: string): Event | undefined {
  return MOCK_EVENTS.find((e) => e.slug === slug);
}
